# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q6AgxZHrJj8Nbf5H-IMoIPMkVs65jdoi
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/supermarket.csv")

# Convert to NumPy arrays
row_id     = df["Row ID"].to_numpy()
category   = df["Category"].to_numpy()
sub_cat    = df["Sub-Category"].to_numpy()
segment    = df["Segment"].to_numpy()
region     = df["Region"].to_numpy()
sales      = df["Sales"].to_numpy()

print("\nRow IDs :")
print(row_id)
print("\nCategory :")
print(category)
print("\nSub-Category :")
print(sub_cat)
print("\nSegment :")
print(segment)
print("\nRegion :")
print(region)
print("\nSales :")
print(sales)

#Total & Average Sales

total_sales   = np.sum(sales)
average_sales = np.mean(sales)

print("\nTotal Sales  :", total_sales)
print("Average Sales:", average_sales)

#Indexing & Slicing

user_input = int(input("\nEnter a Row ID: "))

index_result = df[df["Row ID"] == user_input]

if not index_result.empty:
    print(index_result)
else:
    print("Row ID not found")

print()

start = int(input("Enter the start Row ID: "))
end   = int(input("Enter the end Row ID  : "))

slice_result = df[(df["Row ID"] >= start) & (df["Row ID"] <= end)]
print(slice_result[["Row ID", "Category", "Sub-Category", "Segment", "Region", "Sales"]])

# Statistical Operations
print("\nMean              :", np.mean(sales))
print("Median            :", np.median(sales))
print("Variance          :", np.var(sales))
print("Standard Deviation:", np.std(sales))

#Broadcasting — Sales After Tax (9%)
tax_rate        = 0.09
sales_after_tax = sales * (1 + tax_rate)          # broadcasting scalar to array

df["Sales_After_Tax"] = sales_after_tax

print("\n── Sales After Tax (9%) ──────────────────────────")
print(df[["Row ID", "Category", "Sales", "Sales_After_Tax"]].head(10))

#Vectorized Computation — Category-wise Total Sales

print("\n── Category-wise Total Sales ─────────────────────")
for cat in np.unique(category):
    mask      = category == cat
    cat_total = np.sum(sales[mask])
    cat_avg   = np.mean(sales[mask])
    cat_count = np.count_nonzero(mask)
    print(f"  {cat:<20} | Orders: {cat_count:>4} | "
          f"Total: ${cat_total:>12,.2f} | Avg: ${cat_avg:>8,.2f}")